CREATE TABLE [dbo].[Clientes]
(
	[IdCliente] NUMERIC(20) NOT NULL,
	[Fecha] DATETIME NOT NULL,
	[Categoria] VARCHAR(20) NOT NULL,
	[Peso] INT NULL,
	[Nombre] VARCHAR(50) NOT NULL,
	[Genero] VARCHAR(20) NOT NULL,
	[FechaNac] DATETIME NOT NULL,
	[Nacionalidad] VARCHAR(20) NOT NULL,
	[Correo] VARCHAR(255) NULL,
	[Celular] INT NULL,
	[Particular] INT NULL,
	[Sangre] VARCHAR(10) NULL,
	[Direccion] VARCHAR(255) NULL,
	[NombreCE] VARCHAR(50) NOT NULL,
	[IdCE] NUMERIC(20) NOT NULL,
	[GeneroCE] VARCHAR(20) NOT NULL,
	[FechaNacCE] DATETIME NOT NULL,
	[NacionalidadCE] VARCHAR(20) NOT NULL,
	[CorreoCE] VARCHAR(255) NULL,
	[CelularCE] INT NULL,
	[ParticularCE] INT NULL

	CONSTRAINT [PK_TableClientes] PRIMARY KEY CLUSTERED
	(
		[IdCliente] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
